<?php
/**
 * Created by PhpStorm.
 * User: issa.diao
 * Date: 3/5/2014
 * Time: 10:08 AM
 */

function ips_functions_get_user_data() {

  global $user;
  $user = user_load($user->uid);

  $data = array(
    "company" => '',
    "company_id" => '',
    "logo" => array(),
    "name" => $user->name,
    "image" => array(),
  );

  if (isset($user->picture->uri)) {
    $data['image'] = theme_image_formatter(
      array(
        'item' => array(
          'uri' => $user->picture->uri,
        ),
        'image_style' => 'thumbnail'
      ));
  }

  // add company id, name and logo
  if (isset($user->field_company['und'][0]['target_id'])) {
    $company = node_load($user->field_company['und'][0]['target_id']);
    $data['company'] = $company->title;
    $date['company_id'] = $company->nid;

    if (isset($company->field_image['und'][0]['uri'])) {
      $data['logo'] = theme_image_formatter(
        array(
          'item' => array(
            'uri' => $company->field_image['und'][0]['uri'],
          ),
          'image_style' => 'medium'
        ));
    }
  }

  return $data;
}

function ips_functions_list_all_manufacturers_for_company() {

  $manufacturers = array();

  global $user;
  $user = user_load($user->uid);
  $company = $user->field_company['und'][0]['target_id'];

  if (isset($user->field_company['und'][0]['target_id'])) {
    $result = db_query("SELECT n.nid, n.title
    FROM node n, field_data_field_item_manufacturer dfm, field_data_field_company dfc, node i
    WHERE dfm.field_item_manufacturer_target_id = n.nid
    AND i.type = 'item'
    AND i.nid = dfc.entity_id
    AND i.nid = dfm.entity_id
    AND dfc.field_company_target_id = $company
    GROUP BY n.nid
    ORDER BY n.title
    ");
    foreach ($result as $record) {
      $manufacturers[$record->nid] = $record->title;
    }
  } else {
    // for admin
    $manufacturers[] = "- Any -";
  }

  return $manufacturers;

}

function ips_functions_list_all_departments_for_company() {

  $departments = array();

  global $user;
  $user = user_load($user->uid);
  $company = $user->field_company['und'][0]['target_id'];

  if (isset($user->field_company['und'][0]['target_id'])) {
    $result = db_query("SELECT n.nid, n.title
    FROM node n, field_data_field_item_department dfm, field_data_field_company dfc, node i
    WHERE dfm.field_item_department_target_id = n.nid
    AND i.type = 'item'
    AND i.nid = dfc.entity_id
    AND i.nid = dfm.entity_id
    AND dfc.field_company_target_id = $company
    GROUP BY n.nid
    ORDER BY n.title
    ");
    foreach ($result as $record) {
      $departments[$record->nid] = $record->title;
    }
  } else {
    // for admin
    $departments[] = "- Any -";
  }

  return $departments;

}

function ips_functions_list_all_item_locations_for_company() {

  $locations = array();

  global $user;
  $user = user_load($user->uid);
  $company = $user->field_company['und'][0]['target_id'];

  if (isset($user->field_company['und'][0]['target_id'])) {
    $result = db_query("SELECT n.nid, n.title
    FROM node n, field_data_field_item_location dfm, field_data_field_company dfc, node i
    WHERE dfm.field_item_location_target_id = n.nid
    AND i.type = 'item'
    AND i.nid = dfc.entity_id
    AND i.nid = dfm.entity_id
    AND dfc.field_company_target_id = $company
    GROUP BY n.nid
    ORDER BY n.title
    ");
    foreach ($result as $record) {
      $locations[$record->nid] = $record->title;
    }
  } else {
    // for admin
    $locations[] = "- Any -";
  }

  return $locations;

}

function ips_functions_add_to_inventory($item) {

  global $user;
  $user = user_load($user->uid);

  $node = new stdClass();
  $node->type = 'item';
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->title = $item['name'];
  $node->field_scanner_id['und'][0]['value'] = $item['scanner_id'];
  $node->field_company['und'][0]['target_id'] = $user->field_company['und'][0]['target_id'];
  $node->created = time();
  $node->changed = time();
  $node->uid = $user->uid;
  if (!empty($item['associated_item'])) {
    $node->field_associated_items['und'][0]['target_id'] = $item['associated_item'];
  }
  if (!empty($item['image'])) {
    $file = file_load($item['image']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    file_usage_add($file, 'node', 'node', $user->uid);
    $node->field_image['und'][0]['fid'] = $item['image'];
  }

  node_save($node);

  $log_message = array(
    "nid" => $node->nid,
    "uid" => $user->uid,
    "status" => "Item Created",
    "data" => $node->title . " has been created.",
  );
  ips_item_history_db_insert($log_message);

}








