<?php
/**
 * Created by PhpStorm.
 * User: issa.diao
 * Date: 3/5/2014
 * Time: 10:08 AM
 */

include_once("ips_item_history_data.inc");

function ips_item_history_menu() {

  $items['admin/log'] = array(
    'title' => '100 Most Recent Log Entries',
    'page callback' => 'ips_item_history_display',
    'access callback' => 'user_is_logged_in',
  );

  $items['admin/log/%'] = array(
    'title' => 'All Log Entries For This Item',
    'page callback' => 'ips_item_history_display',
    'page arguments' => array('0', 2),
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

// display 100 most recent log entries
function ips_item_history_display($display = 100, $item = NULL) {
  
  $limit = 'LIMIT 100';
  if ($display == 0) {
    $limit = '';
  }
  
  $nid = '';
  if ($item) {
    $nid = "AND nid = $item";
  }
  
  global $user;
  $user = user_load($user->uid);
  if (isset($user->field_company['und'][0]['target_id'])) {
    $company = 'AND company = ' . $user->field_company['und'][0]['target_id'];
  } else {
    $company = '';
  }

  $output = '<table class="table table-striped table-bordered table-condensed">';
  $output .= '<thead>';
  $output .= '<tr><th>Date</th><th>User</th><th>Item ID</th><th>Title</th><th>Status</th><th>Message</th></tr>';
  $output .= '</thead><tbody>';
  
  $result = db_query("SELECT * 
  FROM item_history 
  WHERE id IS NOT NULL
  $company
  $nid
  ORDER BY id DESC
  $limit
  ");
  foreach ($result as $record) {

    $username = db_query("SELECT name FROM users WHERE uid = :uid", array(":uid" => $record->uid));
    foreach ($username as $name) {
      $user_name = $name->name;
    }
    $node_title = db_query("SELECT title FROM node WHERE nid = :nid", array(":nid" => $record->nid));
    foreach ($node_title as $titled) {
      $title = $titled->title;
    }
    $link = "/admin/log/" . $record->nid;

    $output .= '<tr>';
    $output .= '<td>' . $record->timestamp . '</td><td>' . $user_name . '</td><td>' . $record->nid . '</td><td><a href="'. $link . '">' . $title . '</a></td>';
    $output .= '<td>' . $record->status . '</td><td>' . $record->data . '</td>';
    $output .= '</tr>';
  }
  
  $output .= '</tbody></table>';
  
  return $output;

}