<?php
/**
 * Created by PhpStorm.
 * User: issa.diao
 * Date: 3/5/2014
 * Time: 10:08 AM
 */

include_once("ips_item_history_data.inc");

function ips_item_history_menu() {

  $items['admin/log'] = array(
    'title' => 'Display History Log',
    'page callback' => 'ips_item_history_display',
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

function ips_item_history_display() {

  return "this works for logged in users";

}