<?php
/**
 * Created by PhpStorm.
 * User: issa.diao
 * Date: 3/5/2014
 * Time: 10:08 AM
 */

include_once("ips_item_history_data.inc");

/*
function ips_item_history_entity_postupdate($entity, $entity_type) {

  watchdog("ENTITY", "type = $entity_type and entity = " . print_r($entity,TRUE));

}
*/

function ips_item_history_node_update($node) {

  //watchdog("NODE", "node = " . print_r($node,TRUE));

  $fields = array();
  $originals = array();
  $diff = array();

  foreach ($node as $key => $field) {
    if (substr($key, 0, 6) == "field_") {
      $fields[$key] = $field;
    }
  }

  foreach ($node->original as $key => $original) {
    if (substr($key, 0, 6) == "field_") {
      $originals[$key] = $original;
    }
  }

  foreach ($fields as $key => $new) {
      if (isset($new['und'][0]['value'])) {
        if (isset($originals[$key][0]['und'][0]['value']) && $originals[$key][0]['und'][0]['value'] != $new['und'][0]['value']) {
          $diff[$key] = $new;
        }
      }
  }

  //$diff = array_diff_assoc($originals, $fields);

 // watchdog("FIELDS", "fields = " . print_r($fields,TRUE));
  //watchdog("ORIG", "orig = " . print_r($originals,TRUE));

  watchdog("DIFF", "diff = " . print_r($diff,TRUE));
}