<?php
/**
 * Created by PhpStorm.
 * User: issa.diao
 * Date: 3/5/2014
 * Time: 10:08 AM
 */

function ips_permissions_node_access($node, $op, $account) {

  //watchdog ("permissions", "account = " . print_r($account,TRUE) . " AND NODE = " . print_r($node,TRUE));

  $match = ips_permissions_item_matches_user_company($account->uid, $node->field_company['und'][0]['target_id']);


}

function ips_permissions_item_matches_user_company($uid, $company_id) {

  $user = user_load($uid);
  watchdog("user","company id = $company_id and user= " . print_r($user,TRUE));

}



