<?php
/**
 * Created by PhpStorm.
 * User: issa.diao
 * Date: 3/5/2014
 * Time: 10:08 AM
 */

function ips_permissions_node_access($node, $op, $account) {

  if (isset($node->type) && ($node->type == "item" || $node->type == "grouped_items") && isset($node->field_company['und'][0]['target_id'])) {
    $match = ips_permissions_item_matches_user_company($account->uid, $node->field_company['und'][0]['target_id']);
    if (!$match) {
      return NODE_ACCESS_DENY;
    }
  }

}

// final line of defense. prevent users from viewing/editing nodes from other companies. With only this, they will still see results in searches, etc.
function ips_permissions_item_matches_user_company($uid, $company_id) {

  $user = user_load($uid);
  $user_company = $user->field_company['und'][0]['target_id'];
  if ($user_company == $company_id) {
    return TRUE;
  }

  return FALSE;

}


